### PR TITLE
V4.0.2 German Translation

### PR DESCRIPTION
**Pull request by JoergBruenner**
[OWASP Application Security Verification Standard 4.0.2-final-DE.docx](https://github.com/OWASP/ASVS/files/6096594/OWASP.Application.Security.Verification.Standard.4.0.2-final-DE.docx)

This Pull Request relates to issue #...

This Pull Request provides a complete German Translation of v4.0.2

Greetings
Jörg Brünner

### CODE REVIEW

**Comment by tghosth** [comment]
Hi @JoergBruenner, not sure what happened in this PR but I don't think it is pulling from the correct branch.

I think you previously supplied a translation so is this an update for 4.0.2?
Do you have the markdown files?

**Comment by JoergBruenner** [comment]
Hi Josh,

 > not sure what happened in this PR but I don't think it is pulling
from the correct branch.

Yes, this may be true. I sent Daniel a German translation. He answered:

>> Easiest thing is to do a pull request and we will sort it out,

That's why I made this PR. I saw It was stupid as soon as I was done :-(
I'll need a HowTo
for contributing.

 > Do you have the markdown files?

I translated direct in my Word document of the 4.01 Standard. How to
obtain, how to use the markdown files?

Thanks for help.

Jörg


Am 11.03.2021 um 22:22 schrieb Josh Grossman:

**Comment by tghosth** [comment]
If you look at this fork, you can see how the Spanish translation is being prepared:
https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/es

Presumably, what they did was:

- Forked the repository
- Cloned it to their local disk 
- Copied the markdown files from [https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/**en**](https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/en) to [https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/**es**](https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/es)
- Translated the contents of the files into Spanish.
- Opened a PR from their forked repository to merge their updated files into the main ASVS repository.

In the meantime, is this the updated docx file? [OWASP Application Security Verification Standard 4.0.2-final-DE.docx](https://github.com/OWASP/ASVS/files/6096594/OWASP.Application.Security.Verification.Standard.4.0.2-final-DE.docx)

**Comment by JoergBruenner** [comment]
Hi Josh,

 

thank you for the guide.

 

> In the meantime, is this the updated docx file? OWASP Application Security Verification Standard 4.0.2-final-DE.docx

 

Yes, it is.

 

See You

Jörg

 

Gesendet: Montag, 15. März 2021 um 15:15 Uhr
Von: "Josh Grossman" ***@***.***>
An: "OWASP/ASVS" ***@***.***>
Cc: "JoergBruenner" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [OWASP/ASVS] V4.0.2 German Translation (#912)


 

If you look at this fork, you can see how the Spanish translation is being prepared:
https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/es

Presumably, what they did was:


	Forked the repository
	Cloned it to their local disk
	Copied the markdown files from https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/en to https://github.com/CarlosAllendes/ASVS/tree/v4.0.2/4.0/es
	Translated the contents of the files into Spanish.
	Opened a PR from their forked repository to merge their updated files into the main ASVS repository.


In the meantime, is this the updated docx file? OWASP Application Security Verification Standard 4.0.2-final-DE.docx

**Comment by tghosth** [comment]
Replaced by #949

**Comment by tghosth** [comment]
Thanks @JoergBruenner I have merged that in now.

**Pull request closed without merging**
