### PR TITLE
CONTRIBUTING draft

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issue #...

### CODE REVIEW

**Comment by jmanico** [comment]
Thank you for doing this and I appreciate it!

**Comment by tghosth** [comment]
@elarlang do you have any further comments following my changes?

**Comment by elarlang** [comment]
It's good for starter.

Later, all "how to contribute" question about contributing should be answered/updated to this file.

**Comment by tghosth** [comment]
Ok great, I have dropped it in, thanks @elarlang !!

**Review by Emciu — COMMENTED** [review]
Draft

**Comment by Emciu** [comment]
Ok

**Pull request merged**
