### PR TITLE
Deprecate TLS v1.2

### LINKED ISSUE #979: Deprecate TLS v1.2 for PCI-DSS v3.2.1 Requirement 2.2.3
I would like to propose that OWASP recommend the migration from TLS v1.2 to TLS v1.3 [or later] to support PCI-DSS v3.2.1 Requirement 2.2.3 reproduced below:

image

Therefore, [V9.1 Client Communications Security ](https://github.com/cmlh/ASVS/blob/master/4.0/en/0x17-V9-Communications.md#v91-client-communications-security) will need to be modified.

The alignment with PCI-DSS v3.2.1 is tracked by GitHub Issue https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114

### PR DESCRIPTION
**Pull request by cmlh**
Fix #979

### CODE REVIEW

**Comment by jmanico** [comment]
I see no reason to deprecate TLS 1.2 (yet) in ASVS. If there is a PCI rule or similar please provide a citation. As of today, ssllabs.com and other engines still allow TLS 1.2 at the A+ level and I see no standard or RFC deprecating TLS 1.2.

**Comment by cmlh** [comment]
The [Australian Cyber Security Centre
](https://www.cyber.gov.au/acsc/view-all-content/publications/implementing-certificates-tls-https-and-opportunistic-tls) states "_TLS 1.3 removed vulnerable cipher suites found in TLS 1.2, while introducing stronger cipher suites._" @jmanico

**Comment by jmanico** [comment]
They also say, “If organisations need to use older versions of TLS, care should be taken to select cipher suites and configure protocol features in accordance with this guide and the ISM.”

So no. We are not going to mandate TLS 1.3… yet.

**Comment by cmlh** [comment]
> They also say, “If organisations need to use older versions of TLS, care should be taken to select cipher suites and configure protocol features in accordance with this guide and the ISM.” So no. We are not going to mandate TLS 1.3… yet.

Giving developers a "_preferred option_" will always be "_... vulnerable cipher suites found in TLS 1.2,_" as there is no urgency to upgrade without an enforced requirement @jmanico

**Comment by jmanico** [comment]
While I get your point and think it’s fair - my vote on a TLS 1.3 only requirement today would be no. I’ll certainly vote yes to this in the future, but not now.

**Comment by cmlh** [comment]
> While I get your point and think it’s fair - my vote on a TLS 1.3 only requirement today would be no. I’ll certainly vote yes to this in the future, but not now.

We can meet in the middle if we mandate this for web servers, languages and [web browsers](https://caniuse.com/tls1-3) that support TLS v1.3 since their following major and minor releases:

- [Java 11](https://docs.oracle.com/en/java/javase/11/security/java-secure-socket-extension-jsse-reference-guide.html)
- [Python 3.7](https://docs.python.org/3/library/ssl.html#tls-1-3)
- [Windows Server 2022](https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-)
- [Apache 2.4.38 ](https://downloads.apache.org/httpd/CHANGES_2.4)
- etc

Would this be an alternative you would vote for @jmanico ?  If so then I'll modify this Pull Request.

**Comment by jmanico** [comment]
I cannot endorse forcing TLS 1.3 at this juncture.

**Review by jmanico — COMMENTED** [review]
I strongly oppose forcing the standard to TLS 1.2 - yet. Perhaps in another year.

**Comment by cmlh** [comment]
@jmanico 

> While I get your point and think it’s fair - my vote on a TLS 1.3 only requirement today would be no. I’ll certainly vote yes to this in the future, but not now.

As @jmanico has confirmed this Pull Request is valid then it should be assigned to the future Milestone(s) following 4.1 rather than closed.

**Comment by jmanico** [comment]
This is WAY out in the future, **this PR is staying closed**. But the issue itself can stay open. I do not want PR's lingering for years and this might no go live until 2024.

**Comment by cmlh** [comment]
> This is WAY out in the future, **this PR is staying closed**. But the issue itself can stay open. I do not want PR's lingering for years and this might no go live until 2024.

I can't create another Pull Request from the same Git Commit after this has been closed by @jmanico

**Pull request closed without merging**
