### PR TITLE
V4.0.3 Translation to Portuguese

### PR DESCRIPTION
**Pull request by cesarkohl**

### CODE REVIEW

**Comment by cesarkohl** [comment]
I couldn't push without committing `4.0/cre_mapping_table.md`. It looks like an encoding issue. The content hasn't been changed.

**Comment by elarlang** [comment]
Hi,

fyi: next step is waiting for me and it's validating the structure of the translation. Then we generate all the output formats and set README links etc ourself.

**Comment by elarlang** [comment]
Is it related to https://github.com/OWASP/ASVS/issues/1033 or it is completely separate initiative?

**Comment by cesarkohl** [comment]
@elarlang Hey there! Yes, it's a separate initiative.

**Comment by cesarkohl** [comment]
@elarlang This translation is based entirely on this branch and directory: https://github.com/OWASP/ASVS/tree/v4.0.3/4.0/en

**Comment by elarlang** [comment]
It would be nice to get some formatting things fixed, then it's easier to automate checks.

In big picture it seems good :)


# usage of symbol \x200B

https://www.fileformat.info/info/unicode/char/200b/index.htm

```
grep -r --perl-regexp '\x{200B}' .
```


# space padding

Expected:
```
| # | Descrição | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
```

Sometimes it's weird "padded" (for matchin requirement text length in text editor)
```
| # | Descrição                                                                                                                                                                                                                                                                               | L1 | L2 | L3 | CWE |
| :---: |:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| :---: | :---:| :---: | :---: |
```

Examples:
```
grep -r '   |' .
grep -r '\-\-|' .
```

# 3.4.3

in v4.0.3 CWE is 16, in translation it is 1275.

1275 is correct value, but we translate the document like it is.


# Met some misformated links

V2

```
[tipos de autenticador "restritos"](https://pages.nist.gov/800-63-FAQ/# q-b1)
```

```
[BSI Kryptographische Verfahren: Empfehlungen und Schlussellängen (2018)](https://www.bsi.bund.de/ SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102.pdf?__blob=publicationFile)
```

V3

```
[NIST 800-63b] obrigatório (https://pages.nist.gov/800-63-3/sp800-63b.html)
```

**Comment by cesarkohl** [comment]
Hey @elarlang!

Thanks for your feedback, I applied all your suggestions. In addition to that, I've manually reviewed the grammar using a tool.

Here's the complete list of changes:
- Replace the CWE 1275 with 16
- Remove Unicode character U+200B
- Fix tables headers
- Trim tables contents
- Review grammar
- Fix broken links
- Revert reference links, usually at the bottom of each page, to their original English names. This is what has been applied in other translations.

Last but not least, there's a typo on the English version. In a few tables there's a `| -- |` instead of `| --- |`. This is preventing the correct rendering of tables on Markdown readers. I decided to change it and then ask if this should be changed or if the error should be kept.

I'll be afk for a few days but I'll keep an eye on this PR. Please let me know what needs to be refined in order to merge this PR.

Best,
Cesar

**Comment by elarlang** [comment]
Ok, round 2.

Table syntax correction is ok (`--` vs `---`)

## V6.2 table

6.2.1 - missing `|` after requirement text and before level 1 column
6.2.2 and 6.2.3 - missing `|` or level 1 column in general

See visually: https://github.com/cesarkohl/ASVS/blob/v4.0.3_pt/4.0/pt/0x14-V6-Cryptography.md#v62-algoritmos

## V12.5 title

It is:
```
## Download do arquivo V12.5
```
Should be:
```
## V12.5 Download do arquivo
```

## link in V14

No space needed before URL (problem comes from en version)
```
[OWASP Web Security Testing Guide 4.1: Testing for HTTP Verb Tampering]( https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/03-Testing_for_HTTP_Verb_Tampering.html)
```

## V3.4 spacing

some extra spacing in V3.4 requirements around CWE values

## dash

I'm not sure the used dash symbols are correct way and at the same time I'm pretty sure it's not done correctly in en version neither. It causes some overhead for validation, hopefully it will not influence the output.

(documenting this info for myself/ASVS team)
```sh
ASVS/4.0$ grep -Pr '\x{2013}' . | cut -d':' -f1 | grep '\.md$' | cut -d'/' -f2 | uniq -c
      3 pt
     41 ru
      9 zh-cn
      1 es
      2 fr
     29 en
     33 ar
      2 de

ASVS/4.0$ grep -Pr '\x{2014}' . | cut -d':' -f1 | grep '\.md$' | cut -d'/' -f2 | uniq -c
     74 pt
     61 ru
     15 zh-cn
```

But I think there are some situations, where this symbol is clearly in incorrect place, like in "NIST 800–63". You can find those using:
```
grep -Pr '\x{2013}' . | grep -vP ' \x{2013} '
```

**Comment by elarlang** [comment]
ping @cesarkohl - any plans or intent to make those last changes or you expect those should be handled by us?

**Comment by cesarkohl** [comment]
@elarlang I'll wrap up this PR asap. Thanks for the heads up!

**Comment by cesarkohl** [comment]
@elarlang The requested changes were applied:
- 6.2.1 - missing | after requirement text and before level 1 column
- 6.2.2 and 6.2.3 - missing | or level 1 column in general
- 12.5 title should be ## V12.5 Download do arquivo
- 14 remove space from link
- 3.4 spacing around CWE values
- Replace NIST 800–63 with the simple dash

Regarding the translation, we could go here with just `pt`. Brazilian Portuguese and Portuguese are mostly (like 99%) similar. For instance, Wikipedia has only a single `pt` version. There is no `pt-br`. [https://pt.wikipedia.org/](https://pt.wikipedia.org/)

Probably the Brazilian Portuguese (https://github.com/OWASP/ASVS/issues/1033) PR could be closed after this one is merged.

What are the next steps?

**Comment by cesarkohl** [comment]
On the dash symbol

"There are two types of dashes in Word documents: the en dash (–) and the em dash (—)."

Probably the en dash (the most used is enough. I'm going to replace all em dashes into en dashes for the sake of simplicity. If that's not OK, we can swiftly revert the commit.

**Comment by cesarkohl** [comment]
@elarlang What are the next steps? :)

**Comment by elarlang** [comment]
Next steps:
- I need to recheck is the structure valid
- Then I'll assign task to Josh and he is going to generate all depending documents and update documentation and links
- And then... the World can enjoy ASVS in Portuguese :)

**Comment by cesarkohl** [comment]
Great, I'll be around if you need anything!

**Comment by elarlang** [comment]
Hi @cesarkohl, seems that we have still one round of fixes to go, even I can do those fixes myself as those are not language specific.

## 2.4.4 link
en
```
([C6](https://owasp.org/www-project-proactive-controls/#div-numbering))
```

pt
```
([C6](https://owasp.org/www-project-proactive-controls/#div -numeração))
```


## 2.6 title:
```
## V2.6 Look-up Secret Verifier
```

pt
```
## Verificador secreto de pesquisa V2.6
```


## table 6.2 formating again with tabbing and spacing overhead

Maybe your editor does it automatically when you fixed missing `|` symbols last time?

https://github.com/OWASP/ASVS/pull/1475/commits/3df146854cf0c5643d3e24d6660476f790f21e07#diff-40739f9c7d64feb93992814e0125dcfa368cf7397bf4cf6109bf9dd015758c31

**Comment by cesarkohl** [comment]
Hi @elarlang no worries, just did it!

**Comment by elarlang** [comment]
@tghosth, please check that everything is ok from Git perspective. If it is, then merge but do not generate docs yet. I'll do some whitespace fixing round to make validation easier in the future.

**Comment by tghosth** [comment]
@cesarkohl please can you create a new branch which just provides the translated version and without the change to the README.md and without the weird commit which changes the cre file?

**Comment by cesarkohl** [comment]
@tghosth Here is the requested PR with only the translation files: #1534

**Comment by tghosth** [comment]
Now being tracked by issue https://github.com/OWASP/ASVS/issues/1033#issuecomment-1408776621.

Replaced by #1534.

**Pull request closed without merging**
