### PR TITLE
issue #943

### PR DESCRIPTION
**Pull request by roelstorms**
This Pull Request relates to issue #943

### CODE REVIEW

**Comment by elarlang** [comment]
Based on https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md

Please use:
```
| **1.5.3** | [MOVED TO 5.1.6] | | | | 602 |
```

In 5.1.6 please use label:
```
[MOVED FROM 1.5.3, LEVEL L2 > L1]
```

**Comment by roelstorms** [comment]
Sorry for the error and thanks for verifying. Can you recheck the last commit?

**Comment by elarlang** [comment]
Don't leave any requirement text for 1.5.3, just placeholder:
```
| **1.5.3** | [MOVED TO 5.1.6] | | | | |
```

**Comment by elarlang** [comment]
Seems good now :)

**Comment by roelstorms** [comment]
Thanks for the help!

**Review by jmanico — APPROVED** [review]

**Pull request merged**
