### PR TITLE
Clarify 1.2.4

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1182

### CODE REVIEW

**Comment by tghosth** [comment]
@set-reminder 3 weeks merge if no adverse feedback

**Review by elarlang — CHANGES_REQUESTED** [review]
Comments in issue:
https://github.com/OWASP/ASVS/issues/1182#issuecomment-1359127887

**Comment by tghosth** [comment]
Any further comments @elarlang / @jmanico

**Review by elarlang — APPROVED** [review]

**Comment by tghosth** [comment]
@set-reminder 2 weeks @tghosth to merge if no more comments from @jmanico

**Review by jmanico — APPROVED** [review]

**Pull request merged**
