### PR TITLE
V1-cleansing

### PR DESCRIPTION
**Pull request by tghosth**
Relates to #1460 and #1461 but also addresses other out of scope requirements.

### CODE REVIEW

**Comment by tghosth** [comment]
I agree we need to make these out out of scope items disappear.

**Comment by elarlang** [comment]
I close this PR and I'll open separate one for each requirement, then it's easier to follow, why some changes were made.

Status 1.1.7 is not clear yet and 1.1.1 and 1.1.2 are not analyzed.

**Comment by tghosth** [comment]
Ok, you will open the relevant PRs?

**Comment by elarlang** [comment]
Yes

**Comment by tghosth** [comment]
> Yes

@elarlang see also #1226

**Pull request closed without merging**
