### PR TITLE
V4.0.3 - French translation start

### PR DESCRIPTION
**Pull request by inaz0**
Start of french translation

This Pull Request relates to issue #1209 (https://github.com/OWASP/ASVS/issues/1209)

### CODE REVIEW

**Comment by elarlang** [comment]
What is this PR? Just attempt to translate some files and based on v4.0? (and not v4.0.3)

**Comment by inaz0** [comment]
Just a little part because i'm busy to finish it and other contributor have finish. It's for comparaison with files i have already translated. Not my file was based en 4.0.3

**Comment by elarlang** [comment]
So there is no actual goal for getting it merged to the repository?

If so, I think for comparison you can just share your own fork as well and we can just close this PR. Is that correct?

**Comment by inaz0** [comment]
@elarlang ok i understand i'll close my PR and when the other was accepted i'll made a comparaison after with my work.

**Pull request closed without merging**
