### PR TITLE
Remove the notion of physical tamper or epoxy

### PR DESCRIPTION
**Pull request by tkisason**
Hello everyone,

I would suggest we change the statement 20.18 to say:

* Verify the presence of physical tamper resistance and/or tamper detection features, including epoxy.
into:
* Verify the presence of tamper resistance and/or tamper detection features.

Tamper evidence and tamper resistance are something like security by obscurity, is it useful, yes, should it be used? (yes in addition to other controls and in very specific use-cases)

Here are some arguments why i changed this:
1) If we look at a run off the mill IoT device, what's the possible most likely threat model?
 - Attacker buys X devices, reverse engineers them to find juicy stuff (shared keys, certs, vulnerable SW or vulns in SW, etc) - Tamper evidence or resistance is moot here. Attacker will shave off epoxy, x-ray the device, etc, etc, and won't care for tamper detection. 
 - Attacker has access to a device, for let's say x hours, but needs to return that device to the owner (think interdiction attacks, covert physical or black bag attacks) - This is a specific issue where tamper evidence is welcome, but in the real world it is not really useful or will be useful. Epoxy is a *extremely* dangerous notion, because people think it's the solution to prevent tampering instead of implementing proper secure boot, trusted execution and encrypted storage on modern SoCs devices.

Epoxy as tamper evidence can be easily removed, and even more so, re-applied (in the case of an interdiction attack), so as a tamper-evident measure, it is of dubious value. If you want tamper detection it needs to be implemented like in modern HSMs or POS terminals, that means you implement something like a security mesh around the SoC / Memory, where it will be a physical-hardware method that will wipe the keys from the device or brick the device as a method to prevent extraction or tampering. But for modern SoCs that is not needed since you already have a secure enclave that if used right, makes those attacks very unfeasible.  

Regarding that, i would also consider upping this requirement to L3. Reason - Proper tamper detection is hard, you should implement trusted execution before that (I'll also send some suggestions in pull requests to other points regarding that). In general it is needed only for most critical stuff (PoS terminals, Medical, etc gear)...

Sincerely,
Tonimir

### CODE REVIEW

**Comment by danielcuthbert** [comment]
I fully agree with everything here, you are spot on. I know we need to decide on what we are doing with the IoT section. Do we keep it and reference https://www.owasp.org/index.php/OWASP_Internet_of_Things_Project, or keep it and run the risk that the ASVS standard tries to include all, thus potentially making it a monster?

We do need to make this decision soon imho. @vanderaj & @jmanico thunks?

**Comment by tkisason** [comment]
If you ask me, i would leave it here, until a more mature ASVS for IoT doesn't come along (IoTSVS?). The same thing happened with mobile. ASVS in start contained some baseline tips for mobile applications, afterwards MASVS became a mature project, and that's it, now ASVS references MASVS if you need mobile verification. I say a 1-2 pager for IoT in a very popular document is way better than a 1-2 pager on the wiki that might not get referenced.

**Comment by jmanico** [comment]
Since IoT is out the gate now with the IoT T10 and similar; I’m ok with removing it and pointing to the IoT OWASP project....

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tkisason** [comment]
Sure, but still IoT Top 10 shows top 10 vulnerabilities, and actually doesn't give a succinct guide on what's needed to implement a secure software product that also has a IoT/Embedded component? Those are 2 different things.

**Comment by jmanico** [comment]
Yup. Just saying we have •something• to point to that is recent if we want to.

What about putting the IoT requirements in an appendix so it’s doesn’t mix with WebSec requirements?

Aloha,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
I am going to merge this PR and I have made a note in #357 (the final 4.0 release checklist) to move this section to an appendix per Jim's [comment above](https://github.com/OWASP/ASVS/pull/369#issuecomment-455332384).

**Pull request merged**
