### PR TITLE
50.5.3 Wording improvement per https://github.com/OWASP/ASVS/issues/1873#issuecomment-1958081297

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issue https://github.com/OWASP/ASVS/issues/1873#issuecomment-1958081297

### CODE REVIEW

**Comment by tghosth** [comment]
The wording is still a little tricky, I will try and clean it up next week

**Comment by csfreak92** [comment]
I will try to help with wordsmithing too. The sentence doesn't seem to be complete.

**Comment by tghosth** [comment]
Ok @elarlang what do you think about my wording change to your wording change :)
https://github.com/OWASP/ASVS/pull/1874/commits/b3fd153086d2bc6cd459fb3aac61c025e14d1331

**Comment by elarlang** [comment]
For me, the requirement is still understandable so it is ok. Just let's remove the word "appropriate". I have in my own todo list remove the word from some other requirements as well, just let's not create another one.

**Review by tghosth — APPROVED** [review]

**Pull request merged**
