### PR TITLE
Complement issue #1315 - adding ephemerality req

### PR DESCRIPTION
**Pull request by moshe-apiiro**
This Pull Request relates to issue #1315 - adding ephemerality L3 requirement on top of v14.1

### CODE REVIEW

**Comment by tghosth** [comment]
@moshe-apiiro what do you think about the way I reworded the requirement?

**Comment by moshe-apiiro** [comment]
Looks better aligned with the rest of the text @tghosth . Thanks

**Comment by tghosth** [comment]
@elarlang do you have any comments on this?

**Review by tghosth — APPROVED** [review]

**Comment by tghosth** [comment]
@set-reminder 1 week merge if no further feedback

**Review by jmanico — APPROVED** [review]
Seems reasonable for the DevOps era

**Pull request merged**
