### PR TITLE
Update 2.1.1 requirement

### PR DESCRIPTION
**Pull request by maizuka**
The minimal length of user set password is changed from 12 to 8.

This Pull Request relates to issue #913

### CODE REVIEW

**Comment by elarlang** [comment]
I think there is no point to make pull-request before there is consensus to approve and to make this change happen.

**Comment by jmanico** [comment]
Hey, PR’s always welcome. We have several folks who monitor this stuff so PR away and we’ll discuss it with you before approving it if needed.

We do not require a strict process here and want everyone to contribute as they best feel comfortable.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
Really?

https://github.com/OWASP/ASVS/issues/732

**Comment by jmanico** [comment]
Yes, really. Please break up that massive request into several smaller ones, it will be easier for us to work on it together.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
@jmanico - try to track to which comment/thread you give answer. I think you mix them up. Splitting one big set of requirements to smaller ones is another issue. This one here is clearly - does it make sense to open PR before there is consensus in the issue.

**Comment by maizuka** [comment]
Hi,

My purpose of this PR is that you will apply a change quickly if my suggestion is approved. Sorry for lack of my explanation.

Regards

**Comment by jmanico** [comment]
There is no problem with opening a PR on any issue because we have 4 leaders who need to confirm it before it goes live so it’s no big deal if that’s what you wish to do.

If you want a more detailed discussion then go ahead and do a comment (which is of course our preference) but it’s also ok if you prefer doing a PR, although there is no guarantee it will go live.

In general we really want participants to participate as they see fit. If you notice someone breaking our process then pretty please leave that to leadership team, we will take care of it. 

Aloha,
--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Thank you very much for this contribution. We may not answer right away but it’s in the system for consideration for the next release.

--
Jim Manico
@Manicode

**Comment by elarlang** [comment]
For getting actual meaning and background information for last comments I recommend to join #project-asvs slack channel.

**Comment by jmanico** [comment]
Pardon @maizuka there are merge conflicts on this PR, can you kindly sync to the main branch and do this again? I've made a lot of changes the last few days but we should be much more stable today. Thank you!

**Comment by jmanico** [comment]
Can someone help me resolve conflicts here? @tghosth @elarlang ?

**Comment by maizuka** [comment]
@jmanico Thank you for announce and sorry for delayed. I've resolved the conflict.

**Comment by maizuka** [comment]
@jmanico Thanks for approval. May I close the issue(#913)? I know anybody can reopen if it needs more discussion.

**Comment by jmanico** [comment]
Close it!

--
Jim Manico
@Manicode

**Comment by maizuka** [comment]
@jmanico Sorry for missing [the rule of tags](https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md#use-tags-to-describe-the-change). May I create a new PR to add the tag `[MODIFIED]`?

**Comment by elarlang** [comment]
@maizuka - if you check the latest state of master branch, `[MODIFIED]` tag is there.

And probably you didn't miss the rule of tags, those didn't exist yet when you made this PR :)

**Comment by jmanico** [comment]
Yes please!

**Comment by jmanico** [comment]
And be sure to sync to main, there are many recent changes!

**Comment by JesseMH** [comment]
This still shows as 12 characters in 4.0.3 when it should be 8.

**Comment by jmanico** [comment]
The change to 8 is for the 5.0 branch. We are not modifying 4.x anymore.

**Pull request merged**
