### PR TITLE
V4.0.3 fr

### PR DESCRIPTION
**Pull request by clallier94**
This Pull Request relates to issue #...

### CODE REVIEW

**Comment by elarlang** [comment]
What version it should be?

* 0x00-Header.md - "Application Security Verification Standard 4.0.3" / "Octobre 2021"
* 0x01-Frontispiece.md - "Version 4.0.1, mars 2019"
* 0x02-Preface.md - seems to be 4.0.2

Quick check to actual requirements (from v4.0.3 english):
```
| **1.4.2** | [DELETED, NOT ACTIONABLE] | | | | |
| **1.4.3** | [DELETED, DUPLICATE OF 4.1.3] | | | | |
```

In PR those lines are actual requirements.

It is not clearly correct v4.0.3 translation and structure. Can you please explain, what is it?

Additionally, please fix line breaks to "\n".

**Comment by elarlang** [comment]
* Be sure, that new line character is only "\n" for every file
* Something is not correct with V1.14.* requirements. Compare:
  * https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x10-V1-Architecture.md#v114-configuration-architecture
  * https://github.com/clallier94/ASVS/blob/v4.0.3-fr/4.0/fr/0x10-V1-Architecture.md#v114-configuration-des-exigences-architecturales
* Requirement 7.3.2 got deleted for v4.0.3
  * https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x15-V7-Error-Logging.md#v73-log-protection
  * https://github.com/clallier94/ASVS/blob/v4.0.3-fr/4.0/fr/0x15-V7-Error-Logging.md#v73-exigences-en-mati%C3%A8re-de-protection-des-journaux
* Something is not correct with V13.2.* requirements. Compare:
  * https://github.com/OWASP/ASVS/blob/v4.0.3/4.0/en/0x21-V13-API.md#v132-restful-web-service
  * https://github.com/clallier94/ASVS/blob/v4.0.3-fr/4.0/fr/0x21-V13-API.md#v132-exigences-de-v%C3%A9rification-pour-les-services-web-de-type-restful
* 12.4.1, 14.4.7 different CWE numbers (compared to en version)

**Comment by clallier94** [comment]
[elarlang](https://github.com/elarlang),

it's fixed.

**Comment by clallier94** [comment]
Hello Elar Lang ,

it's fixed.
Thanks for your help.

an example for : "Be sure, that new line character is only "\n" for every
file", please?

Cédric

**Comment by elarlang** [comment]
\n is character which marks line ending, in your files, there is \r\n in use - but I can fix it myself, if needed.

To start finetuning syntax and without first merging it to ASVS master, it would be helpful when you check "allow others to edit" or "draft PR" when you are doing PR.

I'll come back to this more detailly in coming days

**Comment by tghosth** [comment]
@elarlang when you are comfortable with the french translate content, let me know and I will try and figure out how to get it merged into the repo.

**Comment by elarlang** [comment]
Content itself is not something I can verify, as I don't speak any French. 

**I would like to have some other french speaker to verify, that every translated requirement is actually the same requirement both in English and French version.**

I have some doubts on some requirements, like:
* 1.2.2 (missing C3 link in translation) - and maybe mixed with 1.4.4?
* 12.4.1 incorrect CWE number
* 14.4.7 incorrect CWE number (as we changed the requirement text for v4.0.3, please be sure it is up to date as well)

Question: is it some French thing to put whitespace before colon? ` :`

**Comment by clallier94** [comment]
Hello @elarlang ,

for this question : "Question: is it some French thing to put whitespace before colon? :" Yes, it is :)

- 1.2.2 (missing C3 link in translation) - and maybe mixed with 1.4.4? --> **corrected**
- 12.4.1 incorrect CWE number --> **corrected**
- 14.4.7 incorrect CWE number (as we changed the requirement text for v4.0.3, please be sure it is up to date as well) --> **corrected**

I have fixed \n character.

**Comment by tghosth** [comment]
@elarlang I just meant the content questions you had already mentioned, are there any more of those left? In terms of checking the French, I would be tempted to wait until we have a cleaner candidate PR once your other concerns are addressed.

**Comment by elarlang** [comment]
I'll do those tiny syntax finetunings later. At the moment is important to be sure, that all translated requirements actually are matching with English version requirements.

**Comment by tghosth** [comment]
Ok so I have requested confirmation on the French, asked for help in Slack

**Comment by inaz0** [comment]
How can i help in this PR ?

**Comment by elarlang** [comment]
> How can i help in this PR ?

Check, that all requirements in French are matching with requirements in English.

**Comment by inaz0** [comment]
I have finish my pull request waiting @clallier94 validating or rejecting my modification.

**Comment by clallier94** [comment]
Hi all, it's validated!

**Comment by tghosth** [comment]
Thanks @clallier94!

@elarlang were there other checks you wanted to do?

**Comment by elarlang** [comment]
# Missing sections

File: `0x04-Assessment_and_Certification.md`
I think this file is missing 2 last sections (from english version lines 60+).

Missing sections:
* As a Driver for Agile Application Security
* As a Framework for Guiding the Procurement of Secure Software


# Difference in table header

Files: `0x11-V2-Authentication.md`, `0x12-V3-Session-management.md`

In english version in the table header is `[NIST &sect;]`, in translation is `[NIST]`


# Apostrophe

File: `0x11-V2-Authentication.md`

In some places (2.6.1, 2.6.2, 2.6.3) there is symbol `’`, mostly `'` is used.


# `"SameSite"` vs `'SameSite'`

File: `0x12-V3-Session-management.md`

If it is not in conflict in style of writing in French, then please use `'` instead of `"`


# Differences in links

File: `0x13-V5-Validation-Sanitization-Encoding.md`

* original: `* [Angular Security](https://angular.io/guide/security)`
* in translation: `* [Angular Template Security](https://angular.io/guide/template-syntax#content-security)`

I don't know which one is more correct, but till the original is not completely wrong, translated document should point to the same place


File: `0x17-V9-Communications.md`

* original: `* [OWASP - Pinning Guide](https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning)`
* in translation: `* [OWASP - Pinning Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Pinning_Cheat_Sheet.html)`

The same story, like with previous one.

File: `0x22-V14-Config.md`

* original: `* [OWASP Web Security Testing Guide 4.1: Configuration and Deployment Management Testing]`
* in translation: `* [OWASP Testing Guide 4.1: Configuration and Deployment Management Testing]`

Link label missing "Web Security" part

**Comment by clallier94** [comment]
Hi @elarlang, Hi all

Missing sections --> Fixed
Differences in links --> Fixed.

I look for the rest

Good day!

**Comment by clallier94** [comment]
Hi All, @elarlang 

All is done, I think...

Good day

**Comment by elarlang** [comment]
@tghosth , back to you with this one :)

**Comment by tghosth** [comment]
I am going to merge this into a temp branch for testing and then will merge into master if it is successful. Thanks @clallier94 @inaz0 !

**Pull request merged**
