### PR TITLE
Edit for catching good the chapter name

### PR DESCRIPTION
**Pull request by inaz0**
Hi, 

A little modification for the regex to found the chapter name and use it in the export.py script for JSON and other format.

### CODE REVIEW

**Comment by tghosth** [comment]
This PR has a conflict, potentially because this python file changed recently, please can you update your fork and check that it is still relevant. Thanks :)

**Comment by tghosth** [comment]
I'll leave it open while you check

**Comment by inaz0** [comment]
Yes the file changed, so the variable ` prefix_char1_b = ':'` must be to have the value  :  `prefix_char1_b = ''` or to edit all mardown file to add the : after the Vx of chapter name.

**Comment by tghosth** [comment]
@inaz0 in the Arabic translation the : character still seems to be there which is why that section in the export script. As such, I think the change you have made will break the Arabic export process

**Comment by inaz0** [comment]
Ok try to make modification to add ? are optionnal characters

**Comment by tghosth** [comment]
Hi @inaz0 so now looking at https://github.com/OWASP/ASVS/pull/1208/files I am not sure what relevant changes are being made by this PR? Is it still necessary?

**Comment by inaz0** [comment]
Yes i'll confirm it's not necessary ton continue this PR.

**Pull request closed without merging**
