### PR TITLE
Update on 0x10-V1-Architecture.md

### PR DESCRIPTION
**Pull request by csfreak92**
Removal of 1.4.2 - `Verify that the chosen access control solution is flexible enough to meet the application's needs` from V1.4 Access Control Architectural Requirements. 

This Pull Request relates to issue #736 as agreed upon to be removed from the standard.

### CODE REVIEW

**Review by jmanico — CHANGES_REQUESTED** [review]
Can you kindly keep the current numbering system?

For the deleted item, please replace the text with [DELETED] and keep the numbering 

For the modified item can you just add [MODIFIED] before the text of the changed item?

And trouble kick it back to me and I'll take care of it.

**Comment by elarlang** [comment]
https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md

(Link is also available in PR template comments)

**Comment by jmanico** [comment]
Done manually via 480bb9d and closing this out

**Comment by csfreak92** [comment]
Woops, missed your messages on this. Thanks for manually fixing my pull request @jmanico.

**Comment by jmanico** [comment]
You got it, thanks for your contributions @csfreak92

**Pull request closed without merging**
