### PR TITLE
Fix Chapter name parsing with regex

### PR DESCRIPTION
**Pull request by Gby56**
This Pull Request relates to issue #1137
The regex was broken, fixed it !
Glad I could help ! I tested it with https://regex101.com/ and on my personal machine it ran perfectly

### CODE REVIEW

**Comment by jmanico** [comment]
Hey @ike I merged this but can you make sure I did not do so in haste?

**Comment by ike** [comment]
I haven't tested it locally but visual review looks good! If I notice a problem I will report back.

**Comment by Gby56** [comment]
I was surprised there was no Github action triggering an automatic export for testing, just to see if it works properly (I dev on macOS, you never know...)
Could that be interesting for you ? I can take a look

**Comment by Gby56** [comment]
Also I was wondering, will the current 4.0.3 release be updated ? Since the CSV is missing the data.

**Comment by ike** [comment]
> I was surprised there was no Github action triggering an automatic export

We're working on the tooling to support this, right now we don't have automated builds. Feel free to check out the Markdown label for where we're currently at.

**Pull request merged**
