### PR TITLE
Adding 1.1.8 - security.txt requirements

### PR DESCRIPTION
**Pull request by davidclarke-au**
This Pull Request relates to issue #664

### CODE REVIEW

**Comment by tghosth** [comment]
Sorry @davidclarke-au, all changes get pushed to the raw markdown and then the docx, pdf, csv, json, etc can be automatically created using the various scripts. Please cancel this PR and then make the change to the raw markdown here: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x10-V1-Architecture.md

**Comment by davidclarke-au** [comment]
@tghosth please add this to https://github.com/OWASP/ASVS/blob/master/README.md to save any confusions in future, thanks.

**Comment by tghosth** [comment]
@davidclarke-au do you think this commit which will add the note to every new pull request is sufficient: https://github.com/OWASP/ASVS/commit/ed64ead9fd8f18c300b59ea532e1eadf5e36f2fc

**Comment by davidclarke-au** [comment]
@tghosth I think that's appropriate for the PR template, yes. Thank you.

**Pull request closed without merging**
