### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by Marx314**
issue #805

### CODE REVIEW

**Comment by SPoint42** [comment]
Wowww!!!! impressive work need to review ! 
I agree to do a first commit to help review after file/per file before a final build.

**Comment by tghosth** [comment]
This is amazing @Marx314, thanks so much!

I can see there is some review activity going on from @SPoint42 and @chamorin.

I have changed this PR to draft for now so that it is not accidentially merged until review activtity is complete. Please convert back to ready for merge when all reviews are finished.

**Comment by tghosth** [comment]
Hi @Marx314, is this translation complete and reviewed?

**Comment by tghosth** [comment]
Is this now replaced by #849 ?

**Pull request merged**
