### PR TITLE
Clarify entropy meaning and add req with minimum lookup secret entropy

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1218

@elarlang @Sjord would appreciate your review/confirmation.

### CODE REVIEW

**Comment by tghosth** [comment]
I also clarified 2.6.2 based on a simplified interpretation of @jimfenton's comments in #1477

**Review by elarlang — APPROVED** [review]
checked the format, I leave content on you and Sjord

**Comment by tghosth** [comment]
@set-reminder 2 weeks @tghosth to merge if no response from @Sjord

**Review by jmanico — APPROVED** [review]

**Comment by Sjord** [comment]
😐

**Pull request merged**
