### PR TITLE
Update 0x17-V9-Communications.md

### PR DESCRIPTION
**Pull request by csfreak92**
Adding 9.3.3 for mTLS requirement. CWE 295 is the closest I can match this requirement with. 

This Pull Request relates to issue #1382.

### CODE REVIEW

**Review by tghosth — CHANGES_REQUESTED** [review]
1) Do we want to specify that we are talking about internally within the system as opposed to ok every external connection as well.
2) I don't want to use the expression zero trust so I would consider removing that last sentence.

**Comment by csfreak92** [comment]
@tghosth, clarifications on your questions: 

1. I think intra-service communication should be doing mTLS mainly as more applications are in cloud-hosted environments these days, it would improve the security posture of those systems. Regarding have external service-to-service connections, I think you have a point too. So shall I change it to accommodate both internal and external service-to-service connections instead? If that's the case, then it should fall in 9.2.x section then. 
2. I'm just curious as to why you don't like using the zero trust expression in this context? I might be missing something that I do not understand.

**Review by 3m29xp2 — APPROVED** [review]
> `gh pr checkout 

> 1408`

**Comment by tghosth** [comment]
Hi @csfreak92 :)

> I think intra-service communication should be doing mTLS mainly as more applications are in cloud-hosted environments these days, it would improve the security posture of those systems. Regarding have external service-to-service connections, I think you have a point too. So shall I change it to accommodate both internal and external service-to-service connections instead? If that's the case, then it should fall in 9.2.x section then.

To be honest, my point was that we should focus on internal because requiring mTLS for external would be a lot more problematic as it would require all external/3rd party services to support it which is unrealistic.

> I'm just curious as to why you don't like using the zero trust expression in this context? I might be missing something that I do not understand.

It is just a bit of a buzzword that does really mean anything in this context. If you want to give a reason for doing this, we should be more specific.

**Comment by csfreak92** [comment]
@tghosth, I am inclined to agree that we stick with requiring/promoting "intra-service" mTLS communications for now and then re-evaluate that requirement in the future to add in case we decide to have one for external services communicating with each other since that is quite a more problematic task to deal with implementation. 

Regarding zero trust expression, gotcha I will remove that then.

**Comment by csfreak92** [comment]
Updated my PR and commit @tghosth, @elarlang. For your review please.

**Review by tghosth — APPROVED** [review]

**Pull request merged**
