### PR TITLE
Fixed date for OWASP Top 10

### PR DESCRIPTION
**Pull request by digininja**
Date said OWASP Top 10 2018 rather than 2017.

### CODE REVIEW

**Comment by tghosth** [comment]
Thanks @digininja, good spot! I also fixed the original error in commit https://github.com/OWASP/ASVS/commit/3271c25c62d5bc17f35ce257ebd999aa19fa8d3f. 

I will commit an updated PDF soon as well.

If you have any other feedback on the document in general, we would love to hear it. Note that the "master" branch is "bleeding edge" so may have changes which are not in the Word/PDF docs.

**Comment by tghosth** [comment]
PDF fixed in https://github.com/OWASP/ASVS/commit/22f516acf14f90f4ae38e49e9287282e52e428e4

**Comment by digininja** [comment]
Going to be talking through it with a client this week so will let you know if I spot anything else.

**Comment by tghosth** [comment]
Excellent! Hope it goes well!

**Pull request merged**
