### PR TITLE
Remove specifics from level columns in V3.3 Session Termination

### PR DESCRIPTION
**Pull request by Sjord**
Related to #1022.

### CODE REVIEW

**Comment by elarlang** [comment]
With this one I think ASVS should be independent document - if something is taken from NIST and it's part of requirement, then document should duplicate it.

Requirements should be understandable without opening any external document (like NIST in this example).

Removed "30 days | 12 hours or 30 minutes of inactivity, 2FA optional | 12 hours or 15 minutes of inactivity, with 2FA" from requirement must be still covered in ASVS.

**Comment by jmanico** [comment]
I hate to see this info go away. Can we move it somewhere else in the doc?

**Comment by Sjord** [comment]
I added a [table with specifics](https://github.com/OWASP/ASVS/blob/2935cf7d898c06297d3c459e8d86ca494cf27a3b/4.0/en/0x12-V3-Session-management.md#v33-session-termination). What do you think?

**Comment by elarlang** [comment]
I think it makes sense to open separate issue for the discussions on that topic. Discussion over pull-requests is a bit messy.

Provided table gives nice overview, but it makes requirement text itself dependent on document. Maybe there are some other proposals or ways.

**Comment by Sjord** [comment]
Please continue discussion in #1022.

**Pull request closed without merging**
