### PR TITLE
Tried to clarify grammar in 2.8.7 per #1421

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1421

@jmanico please review

@set-reminder 3 weeks @elarlang to review (and ideally merge) if no response

### CODE REVIEW

**Review by jmanico — CHANGES_REQUESTED** [review]
change "and something you know" to "or something you know" and we are there.

**Comment by tghosth** [comment]
@jmanico done, can you or @elarlang approve and merge?

**Comment by jmanico** [comment]
> @jmanico done, can you or @elarlang approve and merge?

I'm done!

**Review by elarlang — CHANGES_REQUESTED** [review]
label MODIFIED instead of GRAMMAR.

**Comment by tghosth** [comment]
label updated

**Comment by tghosth** [comment]
@jmanico @elarlang you both need to approve in order to merge

**Review by jmanico — APPROVED** [review]

**Review by elarlang — APPROVED** [review]

**Pull request merged**
