### PR TITLE
Update 0x14-V6-Cryptography.md

### PR DESCRIPTION
**Pull request by inaz0**
Pinaille sur le mot "cryptée" remplacé par chiffrée

This Pull Request relates to issue #...

### CODE REVIEW

**Review by jmanico — APPROVED** [review]

**Comment by elarlang** [comment]
@tghosth - I leave merge for you as maybe we need to regenerate related docs?

**Comment by tghosth** [comment]
@inaz0, is this critical? Regenerating the output formats is a little time consuming so I am not keen to do it for a single word.

Are there likely to be other changes like this?

**Comment by inaz0** [comment]
Absolutely no critical.

**Comment by tghosth** [comment]
OK so please hold it in a separate branch and submit a PR if you gather a bunch more changes... I will close this for now. 1 day maybe we will have a more efficient build pipeline 🙃

**Pull request closed without merging**
