### PR TITLE
Fixing (and reducing) references to cryptographic salts since approved password storage algorithms handle that for us automatically

### PR DESCRIPTION
**Pull request by jmanico**
Modification of several salt references

### CODE REVIEW

**Comment by jmanico** [comment]
> Related to issue #1002.
> 
> > Password hashing functions take a password and one or more cost factors as inputs when generating a password hash.
> 
> This doesn't add much anymore. Should we remove it?

I removed this sentence from the PR. Looking ok to you?

**Comment by Sjord** [comment]
Does 2.6.2 need a `[MODIFIED]` tag? Other than that, it looks ok.

**Comment by jmanico** [comment]
I’ll fix that tonight!

**Comment by cmlh** [comment]
I feel that this does not reflect the lessons learnt from trusting ESAPI (as one of many examples).

Unless the ASVS verification of the "Password Storage Algorithm" is published then this must be within the scope of ASVS and the ​"Password Storage Algorithm" should be verified against the published reference implementation [and associated supply chain].

Can I ask that this be reconsidered @jmanico please?

**Pull request merged**
