### PR TITLE
Update 0x03-Using-ASVS.md

### PR DESCRIPTION
**Pull request by JoergBruenner**
Changes as mentioned in #1338.

This Pull Request relates to issue #...

### CODE REVIEW

**Comment by tghosth** [comment]
Hi @JoergBruenner , are you going to make the other fixes that @elarlang mentioned?

**Review by jmanico — APPROVED** [review]

**Comment by JoergBruenner** [comment]
Hi @jmanico,

no, I don't plan to do so. Please have a look at my explaination in issue #1338.

See you Jörg

**Comment by elarlang** [comment]
My feedback is written here: https://github.com/OWASP/ASVS/issues/1338#issuecomment-1272359499

**Comment by tghosth** [comment]
@JoergBruenner See my response: https://github.com/OWASP/ASVS/issues/1338#issuecomment-1288132678

**Review by tghosth — CHANGES_REQUESTED** [review]
https://github.com/OWASP/ASVS/issues/1338#issuecomment-1288132678

**Comment by elarlang** [comment]
@tghosth - what is the situation with this PR? via https://github.com/OWASP/ASVS/pull/1369/commits/198fbad6c86cef7a5559b3802eeb0ffd4f538c7b for me it seems to be actually merged? If so, we can just close it.

**Comment by tghosth** [comment]
@elarlang Looks like this PR only has one more change left in it. See here:

https://github.com/OWASP/ASVS/pull/1369/files#diff-906daf6db1db0f7f3d7275c8da8440645e391bc2736ceec9af2372359c812d88

The proposed text seems a little different to the original but it is probably similar enough to be the same, what do you think?

**Review by tghosth — APPROVED** [review]

**Pull request merged**
