### PR TITLE
Standards Mapping Table Between ASVS and CRE

### PR DESCRIPTION
**Pull request by northdpole**
Hey everyone, we discussed adding CRE mappings into a mapping table, keeping with the code-first mentality of both of our projects, I added the ability to opencre.org to export to .md table format.

This PR has been generated from [this table](https://www.opencre.org/rest/v1/standard/ASVS?format_md=true&items_per_page=10000).

Please let me know if this is what you had in mind or if you would like changes

### CODE REVIEW

**Comment by tghosth** [comment]
This PR relates to #1167 and I will continue discussion there.

**Comment by tghosth** [comment]
Waiting for @northdpole to approve my PR on his PR...

**Comment by tghosth** [comment]
This is now waiting for me to add the proper references...

**Comment by tghosth** [comment]
@northdpole I'm sorry this fell between the cracks a little... This is still relevant, right? I

**Comment by northdpole** [comment]
Hey, it is still very relevant, thought we had landed this PR though.

**Comment by tghosth** [comment]
Yeah I think it was nearly there but I wanted to change some links.

I have now done that in #1454

**Pull request closed without merging**
