### PR TITLE
Asvs area51 vol1

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issues:
* #2039 
* #2005 
* #2038
* #2041

### CODE REVIEW

**Comment by elarlang** [comment]
usual ping @randomstuff @TobiasAhnoff

**Comment by tghosth** [comment]
Let me know when you want me to review :)

**Comment by elarlang** [comment]
I prefer those requirements to get in. Those are already improvements what we have now although they are subject to further improvements.

The point and the need is to have clear requirements in the document, not abstract subjects in many parallel issues.

Take it as a development step not a finalizing step.

**Comment by tghosth** [comment]
So don't wait for a review from random and tobias?

**Comment by elarlang** [comment]
No, I got some feedback already in related issues and we will work on them anyway. Just a first patch to get in.

**Review by tghosth — APPROVED** [review]

**Pull request merged**
