### PR TITLE
Area51 vol13 feat V3

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issue
* #2363 
* #2379 
* #2182

### CODE REVIEW

**Comment by tghosth** [comment]
I'm not sure which issue to discuss this in but are sure that 3.5.8 and 51.4.2 cannot be merged together in some way, they are very very similar.

**Comment by elarlang** [comment]
> I'm not sure which issue to discuss this in but are sure that 3.5.8 and 51.4.2 cannot be merged together in some way, they are very very similar.

https://github.com/OWASP/ASVS/issues/2182#issuecomment-2484920111

**Comment by tghosth** [comment]
Added a comment: https://github.com/OWASP/ASVS/issues/2182#issuecomment-2486156018

**Comment by elarlang** [comment]
Updates based on:
* https://github.com/OWASP/ASVS/issues/2182#issuecomment-2488406491
* https://github.com/OWASP/ASVS/issues/2363#issuecomment-2487842250 (but modified based on https://github.com/OWASP/ASVS/issues/2363#issuecomment-2488429020)

**Pull request merged**
