### PR TITLE
Typo and grammatical correction in French ASVS V4

### PR DESCRIPTION
**Pull request by Aif4thah**
Hello,

some additional corrections concerning the French version.

especially for "Bytecode" -> "Code Intermédiaire"

Best regards

### CODE REVIEW

**Comment by Aif4thah** [comment]
The URL checker has failed, but I have not edit any link

**Comment by tghosth** [comment]
Hi @Aif4thah, thanks for your work on this.

Will there be any more fixes which you want to include? I'd rather get them all done together so that I can ask someone to review them all in one go. Thanks!

**Comment by Aif4thah** [comment]
> Hi @Aif4thah, thanks for your work on this.
> 
> Will there be any more fixes which you want to include? I'd rather get them all done together so that I can ask someone to review them all in one go. Thanks!

I understand, I will try to review all the files and make a final PR

**Comment by tghosth** [comment]
Thanks @Aif4thah 

@clallier94 @inaz0 @SPoint42 @Marx314 Please review and let me know if there are any questions

**Review by SPoint42 — APPROVED** [review]

**Comment by SPoint42** [comment]
ok for me

**Review by SPoint42 — APPROVED** [review]

**Comment by inaz0** [comment]
Ok for me

**Comment by tghosth** [comment]
Thanks folks!

**Pull request merged**
