### PR TITLE
Further modifications based on #1250

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1250

@vdbaan @jmanico please make sure you are comfortable with this.

### CODE REVIEW

**Review by vdbaan — APPROVED** [review]
I agree, this is as discussed.

**Comment by tghosth** [comment]
@jmanico please mark this as approved :)

**Comment by elarlang** [comment]
commented to the issue: https://github.com/OWASP/ASVS/issues/1250#issuecomment-1103568982

if anyway change is pushed, change is missing `[MODIFIED]` label

**Review by jmanico — APPROVED** [review]

**Comment by jmanico** [comment]
I love the clarity of this PR, thank you!

**Pull request merged**
