### PR TITLE
V4.0.2 Spanish translation  (based in October 2020, EN release)

### PR DESCRIPTION
**Pull request by CarlosAllendes**
This Pull Request relates to issue #...

### CODE REVIEW

**Comment by Sjord** [comment]
Could you please rename this pull request with a more descriptive title?

**Comment by tghosth** [comment]
Hi @CarlosAllendes, is this now complete?

**Comment by CarlosAllendes** [comment]
Hi  @tghosth  now is OK and complete.

**Comment by CarlosAllendes** [comment]
closing our First translation effort

**Pull request closed without merging**
