### PR TITLE
Changes in section 0x10 and 0x11

### PR DESCRIPTION
**Pull request by javixeneize**
Pull request 409 was rejected as the wrong file was modified

Changes added:

| **1.1.9** | Verify that a there are security requirements and test scenarios to cover the undesired behaviour of the application |  |  | ✓ | tbd | tbd |
| **2.4.13** | Verify that the application allows to use a passphrases as a password. |  |  | ✓ |  |

### CODE REVIEW

**Comment by ronperris** [comment]
@javixeneize 

Did you see this requirement? I think it covers passphrases, or no?

2.4.2 | Verify that passwords 64 characters or longer are permitted.

**Comment by javixeneize** [comment]
Hi. Not specifically. For me, it is a password that is 64 characters long, but does not need to be a passprhase. However, i feel It can be merged under the same requirement

2.4.2 | Verify that passphrases and passwords 64 characters or longer are permitted.

**Comment by jmanico** [comment]
2.4.13 and 2.4.2 are duplicates and passphrases are not relevant (just password size is). I think.

**Comment by jmanico** [comment]
I delted 2.4.13 and am closing this up

**Comment by ronperris** [comment]
@jmanico 

Is it possible that this was accidentally merged? 

Merging this added two new requirements, both new requirements contain typos and don't seem to jive with your comments in this thread.

**Comment by jmanico** [comment]
Ron, I moved too fast. Can you kindly submit a pull request to clean this one up?

**Comment by jmanico** [comment]
I already deleted **2.4.13**

I left **1.1.9** in there (cleaned up) since it seems reasonable... drop it?

**Comment by jmanico** [comment]
So now both 2.4.13 and 1.1.9 are deleted, I added some of 1.1.9 into 1.1.8. We're good, Ron.

**Comment by ronperris** [comment]
@jmanico 👍😃👍

**Pull request merged**
