### PR TITLE
Fix presentation issues with CCM-8 notes

### PR DESCRIPTION
**Pull request by randomstuff**

### CODE REVIEW

**Comment by tghosth** [comment]
Pretty sure those asterisks are there deliberately to reference notes below, do they need escaping?

**Comment by randomstuff** [comment]
Yes, either these should be removed or these should be fixed:

- escaping the leading "*" so that it is not seen as a list item
-  "CCM-8**" →"CCM-8*"

**Comment by tghosth** [comment]
You wanna try and fix?

**Comment by randomstuff** [comment]
Done.

**Comment by tghosth** [comment]
Hi @danielcuthbert please could you review this

**Review by danielcuthbert — COMMENTED** [review]
LGTM!

**Review by tghosth — APPROVED** [review]

**Pull request merged**
