### PR TITLE
Updated 13.5.4 as per #1908

### PR DESCRIPTION
**Pull request by ryarmst**
This Pull Request relates to issue #1908

### CODE REVIEW

**Review by elarlang — COMMENTED** [review]
13.5.4 should start with "Verify that" as the rest of the requirements.

**Comment by ryarmst** [comment]
@elarlang Corrected, thank you.

**Comment by elarlang** [comment]
Thanks for the PR.

FYI: I'll leave this for @tghosth to handle as he was leading the issue, but it may take one week.

**Comment by tghosth** [comment]
Thanks for setting expectations, @elarlang. I actually have some time today so I am going to try and get V13 pushed through.

Thanks @ryarmst for the PR :)

**Pull request merged**
