### PR TITLE
remove incorrect CWE values

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issue #1409

### CODE REVIEW

**Review by tghosth — CHANGES_REQUESTED** [review]
@elarlang is there no CWE that would match in this case?

**Comment by elarlang** [comment]
I have not done any research on that. Just removing the incorrect ones.

**Comment by tghosth** [comment]
OK so let's see if the discussion in #1409 gets anywhere...

**Comment by elarlang** [comment]
Point of view is still the same, to just remove incorrect CWE values.

**Comment by tghosth** [comment]
Do you really think we cannot find a relevant CWE?

**Comment by elarlang** [comment]
as CWE is for weakness identifier, but those requirements coming from policy without being really weaknesses, the answer is yes.

**Review by tghosth — APPROVED** [review]

**Pull request merged**
