### PR TITLE
German translation ready to review

### PR DESCRIPTION
**Pull request by JoergBruenner**
This Pull Request relates to issue #...

### CODE REVIEW

**Comment by elarlang** [comment]
## unneccessary file

File with name:
```
_ __2.2.1__ _ Verify that anti-automation controls are effective at mitigating breached credential testing, brute force,.txt
```

## translator information

I agree with this idea, but we need to keep the document structure the same for every translation.

If we going to change it, we do it for all translated documents the same way.

See related issue https://github.com/OWASP/ASVS/issues/1179

```
## Übersetzung

|                	|
|----------------	|
| Jörg Brünner  	|
```

## File structure

Please keep file structure the same for translated files, including empty lines and chapter levels.

compare:
* <https://raw.githubusercontent.com/JoergBruenner/ASVS/master/4.0/de/0x02-Preface.md>
* <https://raw.githubusercontent.com/OWASP/ASVS/v4.0.3/4.0/en/0x02-Preface.md>

and please keep all the links like they are in English version.

It's important to have identical structure for files, otherwise it's not possible to validate is this structure valid or not.

**Comment by JoergBruenner** [comment]
Hi Elar,

thank you for your answer.

 > unneccessary file

It's removed.

 > translator information

It's removed locally.

 > compare:
 >
https://raw.githubusercontent.com/JoergBruenner/ASVS/master/4.0/de/0x02-Preface.md

 >
https://raw.githubusercontent.com/OWASP/ASVS/v4.0.3/4.0/en/0x02-Preface.md

I changed the empty lines locally.

 > and please keep all the links like they are in English version.

What do you mean? Would you provide an example please? Usually I didn't
touch the titles and links in the references sectors. There is only one
place I added Germany specific information: 0x17-V9-Communications.md

See you
Jörg

Am 14.07.2022 um 19:22 schrieb Elar Lang:

**Comment by elarlang** [comment]
Example for title (`0x02-Preface.md`):
* en: `## What's new in 4.0` (Level 2)
* de: `# Was ist neu in Version 4.0` (level 1)

Example for link ():
en:
```
| **1.1.1** | Verify the use of a secure software development lifecycle that addresses security in all stages of development. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | |
```

de (just text `C1` instead of link):
```
| **1.1.1** | Prüfen Sie, dass der Softwareentwicklungs-Lebenszyklus die Sicherheit in allen Entwicklungsphasen berücksichtigt. (C1)  | | ✓ | ✓ | |
```

**Comment by JoergBruenner** [comment]
I see  thank you. These changes weren't intentionally. I'll check it. Jörg Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Elar Lang ***@***.***> Datum: 15.07.22  12:54  (GMT+01:00) An: OWASP/ASVS ***@***.***> Cc: JoergBruenner ***@***.***>, Author ***@***.***> Betreff: Re: [OWASP/ASVS] German translation ready to review (PR #1317) 

Example for title (0x02-Preface.md):



en: ## What's new in 4.0 (Level 2)

de: # Was ist neu in Version 4.0 (level 1)



Example for link ():

en:

| **1.1.1** | Verify the use of a secure software development lifecycle that addresses security in all stages of development. ([C1](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | |



de (just text C1 instead of link):

| **1.1.1** | Prüfen Sie, dass der Softwareentwicklungs-Lebenszyklus die Sicherheit in allen Entwicklungsphasen berücksichtigt. (C1)  | | ✓ | ✓ | |

**Comment by JoergBruenner** [comment]
Open a new one.

**Pull request closed without merging**
