### PR TITLE
Update 0x11-V2-Authenticaftion.md

### PR DESCRIPTION
**Pull request by csfreak92**
Suggestion to make 2.10.2 better. 

This Pull Request relates to issue #764

### CODE REVIEW

**Comment by Racater** [comment]
The credentials should avoid default values regardless of the account being service or not. I would remove the "service authentication" precision.

**Comment by Sjord** [comment]
> Verify that if passwords are required for service authentication, the service account used is not running on default credentials. (e.g. root/root or admin/admin are default in some services during installation).

I think "running on" is not the proper verb here. Is it sufficiently clear what "default credentials" are? Should we say something like "Verify that passwords are changed from their default after initial installation."

In [another project](http://www.sjoerdlangkemper.nl/2020/09/30/iot-security-regulation/), I phrased it like this, to point more to the actual problem of default passwords:

> After initial setup, passwords must be unique for each device, or defined by the user.

**Comment by tghosth** [comment]
I think it makes sense to focus specifically on service account as that is the point of this section.
@csfreak92 do you agree with the small change I made in 46fd8a0?

**Comment by Racater** [comment]
> I think it makes sense to focus specifically on service account as that is the point of this section.
@tghosth That is a good point.

It is clear that default passwords should not be used for user accounts as well. If this rule is modified to specify "service accounts", a new rule should be added that mentions default passwords (and server-generated passwords). Otherwise, the standard will be weakened.

**Comment by danielcuthbert** [comment]
All good my side and @tghosth is going to merge so as to not break things. Thanks for the effort @csfreak92 :)

**Pull request merged**
