### PR TITLE
Resolve #1324

### LINKED ISSUE #1324: Are 5.2.6 and 12.6.1 effectively duplicates?
Does anyone have a compelling reason why these are not duplicates:

[**V5.2.6**](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x13-V5-Validation-Sanitization-Encoding.md#v52-sanitization-and-sandboxing) | Verify that the application   protects against SSRF attacks, by validating or sanitizing untrusted data or   HTTP file metadata, such as filenames and URL input fields, and uses allow   lists of protocols, domains, paths and ports.

[**V12.6.1**](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x20-V12-Files-Resources.md#v126-ssrf-protection) | Verify that the web or   application server is configured with an allow list of resources or systems   to which the server can send requests or load data/files from.

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1324 

Note CWE change.

### CODE REVIEW

**Comment by elarlang** [comment]
I can not see, how this requirement fits to category "V14.1 Build and Deploy"

**Comment by tghosth** [comment]
It is the closest configuration sub-section, I don't think it is ideal but I am not sure there is any better option...

**Comment by elarlang** [comment]
Can we implement just change for CWE?

I can not see how we can improve current situation with category change. The current one suites better. If we have separate (sub)category for configuration hardening, then it can go there.

**Comment by tghosth** [comment]
@elarlang  I don't think having an SSRF category makes sense, especially with just one requirement which is pretty general anyway. Would you prefer that we start a configuration hardening section in V14?

**Comment by tghosth** [comment]
@elarlang I think I made the changes you wanted here.

**Review by elarlang — CHANGES_REQUESTED** [review]
Can we not use `/` instead of "or"? see https://github.com/OWASP/ASVS/issues/1491

Both, in the subcategory title and in the requirement text

**Comment by tghosth** [comment]
Waiting for: https://github.com/OWASP/ASVS/issues/1491

**Comment by tghosth** [comment]
Do we think this can be merged now @elarlang

**Review by elarlang — APPROVED** [review]

**Comment by elarlang** [comment]
approved, I leave the merge process for you (as there are some conflicts to solve)

**Pull request merged**
