### PR TITLE
Adding 1.1.8 - security.txt requirements

### PR DESCRIPTION
**Pull request by davidclarke-au**
Adding 1.1.8 - security.txt requirements to https://github.com/davidclarke-au/ASVS/edit/master/4.0/en/0x10-V1-Architecture.md

This Pull Request relates to issue #664

### CODE REVIEW

**Comment by tghosth** [comment]
Made some minor tweaks, do you think they look ok?
Also, any idea if there is a relevant CWE number?

**Comment by davidclarke-au** [comment]
> Thanks for the new PR!
> Made some minor tweaks, do you think they look ok?
> Also, any idea if there is a relevant CWE number?

LGTM, I think application is more appropriate. 

I could not find a relevant CWE for this, maybe https://cwe.mitre.org/data/definitions/1110.html thoughts?

**Comment by tghosth** [comment]
How about:
https://cwe.mitre.org/data/definitions/1059.html

**Comment by davidclarke-au** [comment]
That's the parent for 1110, so will probably work better, thanks.

**Comment by davidclarke-au** [comment]
@tghosth I've added a commit to add CWE 1110 to 1.1.8

**Comment by damienbod** [comment]
small note, the `security.txt` can also be placed at the root, not just the well known

**Comment by davidclarke-au** [comment]
> small note, the `security.txt` can also be placed at the root, not just the well known

Quite correct @damienbod , I just used the terminology from the official site, I actually think the root is the better spot for it, as people may naturally search for `tld.com/security.txt`

I will add this reference too, thanks.

**Pull request merged**
