### PR TITLE
Asvs v6 new content from daniel

### PR DESCRIPTION
**Pull request by elarlang**
all in

### CODE REVIEW

**Comment by tghosth** [comment]
I have converted this to draft for now, does it replace the previous PR?

**Comment by elarlang** [comment]
> I have converted this to draft for now, does it replace the previous PR?

yes, we'll close previous one once the comments are moved to issues.

This one gets into the document, #2212 we close.

**Comment by elarlang** [comment]
Ready

**Review by jmanico — APPROVED** [review]

**Review by jmanico — COMMENTED** [review]
6.6.2 is a duplicate of section 2.4.x

**Pull request merged**
