### PR TITLE
Fix grammar of 1.6.4

### PR DESCRIPTION
**Pull request by tghosth**
Reference #1545

### CODE REVIEW

**Review by elarlang — COMMENTED** [review]
`, (such as symmetric keys, passwords, or API tokens,)` - this is really confusing syntax (usage of `(),`), even if it's grammatically correct

**Comment by tghosth** [comment]
What would you prefer? I am willing to be less correct but clearer :)

**Comment by elarlang** [comment]
Verify that the architecture treats client-side secrets (such as symmetric keys, passwords, or API tokens) as insecure and never uses them to protect or access sensitive data.

**Comment by tghosth** [comment]
OK so should be ok now @elarlang

**Review by elarlang — APPROVED** [review]

**Comment by elarlang** [comment]
@jmanico maybe want to verify that, as he opened the issue

**Pull request merged**
