### PR TITLE
Create Security.md

### PR DESCRIPTION
**Pull request by jmanico**
This Pull Request relates to issue #...

### CODE REVIEW

**Comment by danielcuthbert** [comment]
@jmanico love the idea, think we need a hall of fame and also could do with your pgp key somewhere, keybase?

**Comment by jmanico** [comment]
Let's go with KeyBase **jimmanico** 

I will gladly add a hall of fame, I dont think we have any members yet who found security bugs in our scripts, but happy to add anyone!

**Comment by jmanico** [comment]
Thanks @danielcuthbert good stuff. I modified the PR to account for your ideas. Better?

**Review by danielcuthbert — APPROVED** [review]
all good to go

**Pull request merged**
