### PR TITLE
#1309 - security.txt is a recommendation, not a requirement

### PR DESCRIPTION
**Pull request by elarlang**
This Pull Request relates to issue #1309

### CODE REVIEW

**Comment by tghosth** [comment]
Should we move this to a recommendation page so that it does not get lost?

**Comment by tghosth** [comment]
@elarlang what do you think about this addition?

**Comment by tghosth** [comment]
Merge with squash

**Comment by elarlang** [comment]
Looks good to me.

**Comment by tghosth** [comment]
@elarlang did you approve?

**Comment by elarlang** [comment]
As I opened the initial PR, I think you need to approve? :)

**Review by tghosth — APPROVED** [review]

**Comment by tghosth** [comment]
haha yeah you're correct. I feel like that seems like a loophole...

**Pull request merged**
