### PR TITLE
Pull/806

### PR DESCRIPTION
**Pull request by SPoint42**
French (fr_FR) minor corrections

### CODE REVIEW

**Comment by tghosth** [comment]
@SPoint42  @Marx314 does this PR cover the full French translation including #806?

**Comment by SPoint42** [comment]
Yes

**Comment by Marx314** [comment]
it's based on #806 which was based on branch 4.0.2 from mid-June 2020.

**Comment by SPoint42** [comment]
> it's based on #806 which was based on branch 4.0.2 from mid-June 2020.

Right

**Comment by tghosth** [comment]
Thanks @SPoint42 @Marx314, maybe have a quick check that there are no 4.0.2 changes since then. I am determined to get 4.0.2 finished by the end of this month.

https://github.com/OWASP/ASVS/compare/6d6978af732d66a469cd87f7430f12b3a9ec4bb3...5c7a929a3fadba47c67e5e2b677b59fb307d9875

**Comment by tghosth** [comment]
I am merging this now so we can use it as an experiment for our automation work. However, I would quite like a confirmation from @SPoint42 @Marx314 so as to make sure that it is up to date, at least with 4.0.2.

**Pull request merged**
