### PR TITLE
Clarify 6.2.6 based on @jmanico's point in #1378

### PR DESCRIPTION
**Pull request by tghosth**
This Pull Request relates to issue #1378

@jmanico please review :)

### CODE REVIEW

**Comment by tghosth** [comment]
@set-reminder 3 weeks @elarlang to review (and merge if possible) if no response from @jmanico

**Review by jmanico — CHANGES_REQUESTED** [review]
I like the wording but suggest L3 only, it's a hard core requirement.

**Comment by elarlang** [comment]
Related - we should have some clear understanding when, why and how we use `/`, I opened related issue: https://github.com/OWASP/ASVS/issues/1491

**Comment by tghosth** [comment]
@elarlang please can you review

**Review by elarlang — APPROVED** [review]

**Comment by tghosth** [comment]
> I like the wording but suggest L3 only, it's a hard core requirement.

hi @jmanico, you need to specifically approve this before GitHub will allow it to be merged :) This has been changed to L3

**Review by jmanico — APPROVED** [review]

**Pull request merged**
