### PR TITLE
Add portuguese translation files

### PR DESCRIPTION
**Pull request by tghosth**
Opening this as a placeholder but we are waiting for @elarlang to perform final checks on the translation and then for me to generate the outputs.

### CODE REVIEW

**Review by elarlang — APPROVED** [review]

**Comment by elarlang** [comment]
ping @tghosth

**Comment by cesarkohl** [comment]
ping @tghosth 🙂

**Comment by tghosth** [comment]
UndertakerCasketGIF

OK, things have been a little busy but I am hoping to get back in the game a little now....

I have added the PDF output [to here](https://github.com/OWASP/ASVS/blob/master-pt-translation/4.0/OWASP%20Application%20Security%20Verification%20Standard%204.0.3-pt.pdf) and the other output formats [to here](https://github.com/OWASP/ASVS/tree/master-pt-translation/4.0/docs_pt).

@cesarkohl please can you verify that they look ok before I merge everything in.

**Comment by cesarkohl** [comment]
@tghosth @elarlang I reviewed all pages.

It's so cool to see the PDF. Last December, when I started working on this translation I wondered if I could finish it. Now it's here and soon to everyone else.

I'm proud to have achieved this with you all. It has been a pleasure, gentlemen. :)

**Pull request merged**
